require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    - bin/**/*
    - db/**/*
    - db/schema.rb
    - vendor/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
