default: &default
  adapter:  postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mp
  password: <%= ENV['CHALLENGE_DATABASE_PASSWORD'] %>

development:
  <<: *default  
  database: challenge1_development
  

